#!/bin/bash
MAX_ATTEMPTS=300
ATTEMPTS=0

i=1
sp="/-\|"
echo -n ' '

USAGE="Usage: $0 [PORT…]"

PORTS=(${ARGV[@]})
if [ "$#" == "0" ]; then
    PORTS=(5888)
    echo $USAGE
fi

for (( i=0; i < ${#PORTS[@]}; i++ )); do
    PORT=${PORTS[$i]}
    echo "Waiting for connection on port ${PORT}…"

    while ! nc -z localhost $PORT && (( ATTEMPTS < MAX_ATTEMPTS )); do
        ATTEMPTS=$((ATTEMPTS + 1))
        printf "\b${sp:i++%${#sp}:1}"
        sleep 0.5
    done

    if  (( ATTEMPTS < MAX_ATTEMPTS )); then
        echo "Connection ready"
    else
        exit 1
    fi
done
