#!/bin/bash
MAX_ATTEMPTS=300
ATTEMPTS=0

USAGE="Usage: $0 PORT [PORT…]"
if [ "$#" == "0" ]; then echo $USAGE && exit 1; fi

i=1
sp="/-\|"
echo -n ' '

while (( "$#" )); do
    PORT=$1; shift
    echo "Waiting for connection on port ${PORT}…"

    while ! nc -z localhost $PORT && (( ATTEMPTS < MAX_ATTEMPTS )); do
        ATTEMPTS=$((ATTEMPTS + 1))
        printf "\b${sp:i++%${#sp}:1}"
        sleep 0.5
    done

    if  (( ATTEMPTS < MAX_ATTEMPTS )); then
        echo "Connection ready"
    else
        exit 1
    fi
done
